check/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include("accounts.urls")),
    path("social-auth/",include("social_django.urls",namespace="social")),
    path("images/",include("images.urls",namespace="images")),
    path("",include("homesite.urls",namespace="home")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path

from .views import image_create,image_detail,image_like
from .views import image_list


app_name = "images"

urlpatterns = [
    path("create/",image_create,name="create"),
    path("image-detail/<int:id>/<slug:slug>/",image_detail,name="image_detail"),
    path("like/",image_like,name="like"),
    path("bookmarked-images/",image_list,name="list"),
]

images/models.py
from django.db import models

from django.utils.text import slugify
from django.urls import reverse,reverse_lazy
from django.conf import settings


# Create your models here.

class Image(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="images_created")

    title = models.CharField(max_length=450)

    slug = models.SlugField(max_length=450,blank=True)

    image = models.ImageField(upload_to="bookmarks/%y/%m/%d")

    description = models.TextField(blank=True)

    url = models.URLField()

    created = models.DateTimeField(auto_now_add=True)

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name="images_liked",blank=True)

    def __str__ (self):
        return self.title

    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super(Image,self).save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse ("images:image_detail",args=[self.id,self.slug])

images/forms.py
from django import forms

from .models import Image

from urllib import request

from django.core.files.base import ContentFile

from django.utils.text import slugify


class ImageCreationForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ["title","url","description"]
        widgets = {
            'url':forms.HiddenInput,
        }

    def clean_url (self):

        url = self.cleaned_data['url']

        valid_extensions = ["jpg","jpeg","png"]

        extension = url.rsplit(".",1)[1].lower()

        if extension not in valid_extensions:
            raise forms.ValidationEror("The given URL does not match any valid image extensions\nThe valid extensions ar jpg jpeg png")

        return url

    def save(self,force_insert=False,force_update=False,commit=True):

        image = super(ImageCreationForm,self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = "{}.{}".format(slugify(image.title),image_url.rsplit(".",1)[1].lower())

        #download image from the URL

        response = request.urlopen(image_url) # we get the the address of the image
        image.image.save(image_name,ContentFile(response.read()),save=False)

        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404

from .forms import ImageCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Image

from django import forms

from django.http import JsonResponse
from django.views.decorators.http import require_POST

from common.decorators import ajax_required

from django.http import HttpResponse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views here.

@login_required
def image_create(request):

    if request.method == "POST":
        image_form = ImageCreationForm(data=request.POST)

        if image_form.is_valid():
            cd = image_form.cleaned_data
            new_image = image_form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            messages.success(request,"Image upload success")
            return redirect(new_image.get_absolute_url())

        else:

            messages.error(request,"Image upload failed")
            raise forms.ValidationEror("Something went wrong.")

    else:
        image_form = ImageCreationForm(data=request.GET)

    return render(request,"images/create_image.html",{"image_form":image_form,"section":"images"})


def image_detail(request,id,slug):
    image = get_object_or_404(Image,id=id,slug=slug)

    return render(request,"images/image_detail.html",{"section":"images","image":image})

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')

    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})

@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images,5)
    page = request.GET.get('page')

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse("")

        images = paginator.page(paginator.num_pages)

    if request.is_ajax():
        return render(request,"images/list_ajax.html",{"section":"images","images":images})

    return render(request,"images/list.html",{"section":"images","images":images})

images/templates/images/create_image.html
{% extends 'site/base.html' %}


{% block title %}Bookmark Image {% endblock title %}

{% block content %}

  <h3>Bookmark an image</h3> <hr>
  <img src="{{request.GET.url}}" alt="image-preview" width="300px" height="200px">
  <form class="" action="." method="post">
    {% csrf_token %}
    {{image_form.as_p}}
    <button type="submit" name="button">Bookmark it!</button>
  </form>

{% endblock content%}

images/templates/images/image_detail.html
{% extends 'site/base.html' %}
{% load thumbnail %}


{% block title %}{{image.title}} {% endblock title %}

{% block domready %}
  $('a.like').click(function(e){
    e.preventDefault();
    alert("work");
    $.post('{% url "images:like" %}',
      {
        id: $(this).data('id'),

        action: $(this).data('action')
      },
      function(data){
        if (data['status'] == 'ok')
        {
          var previous_action = $('a.like').data('action');

          // toggle data-action
          $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
          alert("middle");
          // toggle link text
          $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');

          // update total likes
          var previous_likes = parseInt($('span.count .total').text());
          $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
          alert("updated");
        }
      }
    );
  });
{% endblock %}


{% block javascript %}
  <script>
    var model = document.getElementById("bookmark-photo-view-full");
    var img = document.getElementById("bookmark-photo-view");
    var modelimg = document.getElementById("bookmark-photo-view-img");
    var caption = document.getElementById("caption");

    img.onclick = function () {
        model.style.display = "block";
        modelimg.src=this.src;
        caption.innerHTML=this.alt;

    }

    var imgclose = document.getElementById("close");
    imgclose.onclick = function() {
      model.style.display = "none";
    }

  </script>
{% endblock %}



{% block content %}

  <h1>{{image.title}}</h1> Bookmarked by {{image.user}} <hr>

  {% thumbnail image.image '300' as im %}
    <img class="bookmark-photo-view" id="bookmark-photo-view" src="{{im.url}}" alt="{{image.title}}" width="300px" height="200px">
  {% endthumbnail %}
  <a href="{{image.image.url}}" download="{{image.title}}">Download HD Image</a>
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}

    <div class="image-info">
      <div class="count">
        <span class="total">{{total_likes}} like{{total_likes|pluralize}}</span>
        <span>follower</span>
        <a href="#" data-id="{{image.id}}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like-button">
          {% if request.user not in users_like %}
            Like
          {% else %}
            Unlike
          {% endif %}
        </a>
        <p style="color:red;">pending image like script</p>
      </div>
      <p>{{image.description}}</p>
    </div>
    <div class="images-liked-by-others">
      <h3>Image liked by others</h3> <hr>
      {% for user in image.users_like.all %}
        <div class="liked-user-info">
          <img src="{{user.profile.photo.url}}" alt="{{user.first_name}}" width="70px" height="70px">
          <p>{{user.first_name}}</p>
        </div>
      {% empty %}
        No body likes this image yet.
      {% endfor %}
    </div>

  {% endwith %}



  <div class="bookmark-photo-view-full" id="bookmark-photo-view-full">
    <span id="close" class="close">&times;</span>
    <img id="bookmark-photo-view-img" class="bookmark-photo-view-img">
    <div id="caption"></div>
  </div>


{% endblock content %}

images/templates/images/list.html
{% extends 'site/base.html' %}

{% block title %}Bookmarked images {% endblock title %}

{% block domready %}

  var page = 1;
  var empty_page = false;
  var block_request = false;

  $(window).scroll(function() {
    var margin = $(document).height() - $(window).height() - 200;
    if ($(window).scrollTop() > margin && empty_page == false && block_request == false){
      block_request = true;
      page +=1;
      $.get("?page=" + page, function(data) {
        if (data == "") {
          empty_page = true;
        }
        else {
          block_request = false;
          $("#image-list").append(data);
        }
      });
    }
  });


{% endblock %}

{% block content %}

  <h2>Here the All Bookmarked Images</h2><hr>
  <div class="image-list" id="image-list">
    {% include "images/list_ajax.html" %}
  </div>

{% endblock content %}

images/templates/images/list_ajax.html
{% load thumbnail %}

{% for image in images %}

  <div class="images">
    <a href="{{ image.get_absolute_url }}">
      {% thumbnail image.image "300x300" corp="100%" as im %}
        <a href="{{image.get_absolute_url}}">
          <img src="{{im.url}}" alt="">
        </a>

      {% endthumbnail %}
    </a>
    <div class="info">
      <a href="{{image.get_absolute_url}}" class="title">{{image.title}}</a>
    </div>
  </div>



{% endfor %}