accounts/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views


from .views import AccountsSiteHome,user_register,validate_user_register
from .views import update_profile,AccountDetails


urlpatterns = [
    path("login/",auth_views.LoginView.as_view(),name="login"),
    path("logout/",auth_views.LogoutView.as_view(),name="logout"),
    path("password_change/",auth_views.PasswordChangeView.as_view(),name="password_change"),
    path("password_change/done/",auth_views.PasswordChangeDoneView.as_view(),name="password_change_done"),
    path("password_reset/",auth_views.PasswordResetView.as_view(),name="password_reset"),
    path("password_reset/done/",auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    path("password_reset/<uidb64>/<token>/confirm/",auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path("password_reset/complete/",auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
    path("",AccountsSiteHome.as_view(),name="home"),
    path("create-account/",user_register,name="create_account"),
    path("validate-user-form/",validate_user_register,name="validate_user_register"),
    path("account-details/",AccountDetails.as_view(),name="account_details"),
    path("update-profile/",update_profile,name="update_profile"),

]

check/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include("accounts.urls")),
    path("social-auth/",include("social_django.urls",namespace="social")),
    path("images/",include("images.urls",namespace="images")),
    path("",include("homesite.urls",namespace="home")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

homesite/urls.py
from django.urls import path


from .views import Homepage

app_name = "home"

urlpatterns = [
    path("",Homepage.as_view(),name="home_page"),
]

images/urls.py
from django.urls import path

from .views import image_create,image_detail,image_like
from .views import image_list


app_name = "images"

urlpatterns = [
    path("create/",image_create,name="create"),
    path("image-detail/<int:id>/<slug:slug>/",image_detail,name="image_detail"),
    path("like/",image_like,name="like"),
    path("bookmarked-images/",image_list,name="list"),
]

accounts/models.py
from django.db import models

from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    date_of_birth = models.DateField(blank=True,null=True)

    photo = models.ImageField(upload_to="users/%y/%m/%d",default="Default_avthar.png",blank=True,null=True)

    gender_choices = (("Male","Male"),("Female","Female"),("Other","Other"),("Not_specified","Not Specified"))

    gender = models.CharField(max_length=15,choices=gender_choices,default="Not_specified",blank=True,null=True)

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

    def __str__ (self):
        return "Profile for user {}".format(self.user.username)

accounts/forms.py
from django import forms

from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(forms.ModelForm):

    password = forms.CharField(label="Password",widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password",widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username',"email","first_name"]
        widgets = {
            'username':forms.TextInput(attrs={
                'required':True,
                'placeholder':"Username"
            }),
            'first_name':forms.TextInput(attrs={
                'required':False,
                'placeholder':"First Name"
            }),
            "email":forms.TextInput(attrs={
                'required':True,
                'placeholder':"Email"
            })
        }

        def clean_password(self):
            cd = self.cleaned_data

            if cd['password'] != cd['password2']:

                raise forms.ValidationEror("Passwords didn't match please try again.")

            return cd['password2']

        def clean_email(self):
            email = self.cleaned_data.get('email')
            username = self.cleaned_data.get("username")

            email_check = User.objects.filter(email__iexact=email).exists()

            if email_check:
                raise forms.ValidationEror("The given Mail is already taken. Please try another one.")


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name","last_name","email"]

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["date_of_birth","photo","gender"]

accounts/views.py
from django.shortcuts import render

from django.views.generic import TemplateView,ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView

from django.contrib.auth.models import User

from .forms import UserRegistrationForm

from django.http import JsonResponse

from .models import Profile
from .forms import UserEditForm,ProfileEditForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.urls import reverse,reverse_lazy

# Create your views here.

class AccountsSiteHome(TemplateView):
    template_name = "site/home.html"


def user_register(request):

    if request.method == "POST":
        user_form = UserRegistrationForm(data=request.POST)

        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            # setting the user wanted password
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user) # Custom user register user form extension

            return render (request,'accounts/user_register_done.html',{"new_user":new_user})

    else:
        user_form = UserRegistrationForm()

    return render(request,"accounts/user_register.html",{"user_form":user_form})

def validate_user_register(request):

    username = request.GET.get('username',None)
    email = request.GET.get('email',None)

    data = {
        'is_taken':User.objects.filter(username__iexact = username).exists(),
        'mail_taken': User.objects.filter(email__iexact = email).exists(),
    }

    if data['is_taken']:
        data['error_message'] = "The requested username is already taken"
    elif data['mail_taken']:
        data['mail_error'] = "The given mail is already taken. Please try another one."

    return JsonResponse(data)



class AccountDetails(LoginRequiredMixin,TemplateView):
    template_name = "accounts/account_details.html"

@login_required
def update_profile(request):
    if request.method == "POST":

        user_form = UserEditForm(instance=request.user,data=request.POST)

        profile_form = ProfileEditForm(instance = request.user.profile,data=request.POST,files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,"Profile updated successfully.")

            return render(request,"accounts/account_details.html")
        else:
            messages.error(request,"Profile update Fail. Please try again.")

    else:
        try:
            user_form = UserEditForm(instance=request.user)
            profile_form = ProfileEditForm(instance=request.user.profile)
            return render (request,"accounts/update_profile.html",{"user_form":user_form,"profile_form":profile_form})

        except :
            return render (request,"accounts/update_profile.html",{"user_form":user_form})

accounts/templates/site/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'accounts/css/base.css' %}">
  </head>
  <body>
    <header>
      <div class="site-urls">
        <ul>
          <li>
            <a href="{% url 'home' %}">Account</a>
          </li>

          <li>
            <a href="{% url 'home:home_page' %}">Home</a>
          </li>

          <li>
            <a href="#">About</a>
          </li>

          <li>
            <a href="{% url 'images:list' %}">Images</a>
          </li>

          <li>
            <a href="#">People</a>
          </li>

        </ul>
      </div>

      <div class="authentication-urs">
        {% if user.is_authenticated %}
          <p>Hi! {{user.username}} <span id='logout'><a href="{% url 'logout' %}">Logout</a></span> <span  id="password_change"><a href="{% url 'password_change' %}">Change password</a></span></p>
        {% else %}
          <p> <a href="{% url 'login' %}">Login</a></p>
        {% endif %}
      </div>
    </header>

    {% if messages %}
    <ul id='messages'>
      {% for message in messages %}
        <li>
          {{message|safe}}
          <a id="close" href="#">X</a>
        </li>
      {% endfor %}
    </ul>
    {% endif %}

    <div class="block-content">
      {% block content %}
      {% endblock content %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'accounts/js/app.js' %}"> </script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
    {% block javascript %}

    {% endblock %}

    <script>
      var csrftoken = Cookies.get('csrftoken');

      function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));

      }

      $.ajaxSetup({
        beforeSend: function(xhr,settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken",csrftoken);
          }
        }
      });


      $(document).ready(function() {
        {% block domready %}

        {% endblock %}
      });
    </script>

  </body>
</html>

accounts/templates/site/home.html
{% extends 'site/base.html' %}

{% block title %}Accounts Home {% endblock title %}


{% block content %}

  {% if user.is_authenticated %}
    <p>Here your account Details</p> <hr>
    <a href="{% url 'update_profile' %}" target="_blank">Update profile</a>
    <a href="{% url 'account_details' %}">Account Details</a>
  {% else %}
    <h2>You must login to see your account details</h2> <hr>
    <a href="{% url 'login' %}">Login</a>
  {% endif %}


{% endblock content %}